### ISSUE TITLE
Contribution request

### ISSUE THREAD

**Issue by starride-teklia** [jpuigcerver/nnutils#7]
Hi Joan,
Could you add me and @La0 as contributors on this project? We would like to release wheels to support the latest Pytorch version. This would allow us to bump Pytorch for PyLaia as well.
Thanks,
Solène

**Comment by jpuigcerver** [comment]
Done!

**Comment by La0** [comment]
Looks like we missed the invite, I still cannot merge the PR !6 from @starride-teklia .

Could you retry @jpuigcerver ? Sorry about that

**Comment by jpuigcerver** [comment]
I just sent the invite again.

**Comment by La0** [comment]
Thanks a lot, I was able to merge !6
